### ISSUE TITLE
获取不到文章？！

### ISSUE THREAD

**Issue by starstealing** [laowch/GithubTrends#14]
请问，难道是接口换了吗？

**Comment by laowch** [comment]
服务器被墙了，暂时无法恢复

**Comment by laowch** [comment]
建议部署到自己的服务器上 @starstealing  

服务端代码在这里
https://github.com/laowch/github_trends_server

**Comment by starstealing** [comment]
我翻墙后，还是无效，python3下运行你那个代码有问题，麻烦作者能不能把那个服务器给修复好。谢谢了。
