### ISSUE TITLE
Bug when add  new language

### ISSUE THREAD

**Issue by NamPNQ** [laowch/GithubTrends#3]
When i choose C++, it's auto choose Julia, SyperColider, I guess u copy code and forgot edit ;)

**Comment by laowch** [comment]
I checked it, and it works well.

Does this problem reappear frequently?

Or only in some specific operation?

**Comment by NamPNQ** [comment]
Hi @laowch 

I had create video for you:
https://drive.google.com/file/d/0B3jNXd3gkCRZeVF1dVJ2bXFieXM/view?usp=sharing

My OS: Android M

Version: Latest in google store

**Comment by laowch** [comment]
I fixed it.
Thanks for report.
